### PR TITLE
Add default option code when connect and add utf8 as a default option.

### PR DESCRIPTION
**Pull request by pascalr0410**
Hello,

Sorry for my bad english.

This Pull request for : 

- add a list of default option to set when connecting to the db server
- add an option to force the server to interpret string as utf8 format, the default in Julia

If this option is not forced, the client determine the string format to utilise using system default and this may cause undeterminated comportement in function of the underlying OS. On european Windows, the default is latin1 and this cause missunderstanding of Julia utf8 string by the db server.

this may be mitigated by sending the above command after connexion but, in my sense, it may be more usefull to integrate this directly into the module.

MySQL.execute!(cnx, "set character_set_client='utf8';")

This is my test case :

Current module : 

include("EnvVar.jl")
using DataFrames, MySQL

My pull request :

include("EnvVar.jl")
include("../MySQL.jl/src/MySQL.jl")
using DataFrames, .MySQL

cnx = MySQL.connect(env.key["MySQLHost"], env.key["MySQLUser"], env.key["MySQLPass"], db=env.key["MySQLDb"])
df = MySQL.query(cnx, "SHOW SESSION VARIABLES LIKE 'character\\_set\\_%';", DataFrame)
MySQL.disconnect(cnx)

Results

My pull request :

│ Row │ Variable_name            │ Value  │
│     │ String                   │ String │
├─────┼──────────────────────────┼────────┤
│ 1   │ character_set_client     │ utf8   │
│ 2   │ character_set_connection │ utf8   │
│ 3   │ character_set_database   │ latin1 │
│ 4   │ character_set_filesystem │ binary │
│ 5   │ character_set_results    │ utf8   │
│ 6   │ character_set_server     │ latin1 │
│ 7   │ character_set_system     │ utf8   │

Current module : 

│ Row │ Variable_name            │ Value  │
│     │ String                   │ String │
├─────┼──────────────────────────┼────────┤
│ 1   │ character_set_client     │ latin1 │
│ 2   │ character_set_connection │ latin1 │
│ 3   │ character_set_database   │ latin1 │
│ 4   │ character_set_filesystem │ binary │
│ 5   │ character_set_results    │ latin1 │
│ 6   │ character_set_server     │ latin1 │
│ 7   │ character_set_system     │ utf8   │

### CODE REVIEW

**Comment by pascalr0410** [comment]
This may be related to #109 issue.

**Comment by mcmcgrath13** [comment]
@pascalr0410 based on some recent experience with this, I think the default should be "utf8mb4" as the current MySQL default is utf8mb3 for "utf8".  I think they're changing this over in the future, but to be safe, probably better to be more specific.

**Comment by pascalr0410** [comment]
@mcmcgrath13 you are right, I have updated the PR.

**Comment by quinnj** [comment]
@pascalr0410 and @mcmcgrath13, sorry this PR languished; this is a good change and I've incorporated setting the default charset in https://github.com/JuliaDatabases/MySQL.jl/pull/139 where I'm overhauling the whole package.

**Pull request closed without merging**
