### PR TITLE
avoid NamedTuple{names, types}, fix #130

### LINKED ISSUE #130: Very poor performance on query with many fields but few rows [v0.7.0]
I'm very disappointed by the performance of queries with many columns but only very few rows. These are my observations:

I have a MySQL table with many rows and 26 fields:

```SQL
MySQL [mydb]> select count(*) from my_table;
+----------+
| count(*) |
+----------+
|   812611 |
+----------+
1 row in set (0.29 sec)
```

I'm observing very poor performance on MySQL queries with many columns on this table, even when I `LIMIT` the number of rows **to only 100 rows**!

This is the Julia code I'm running inside the REPL:

```Julia
julia> using MySQL; conn = MySQL.connect("X.X.X.X","root","XXX",db = "mydb")
MySQL Connection
------------
Host: X.X.X.X
Port: 3306
User: root
DB:   mydb

julia> fields = [...] # string array containing the 26 field names
julia> for i in 2:length(fields)-1
           print(i)
           @time for x in MySQL.Query(conn, "select $(join(fields[1:i], ",")) from my_table limit 100;", streaming=true); print("."); end
       end
# I truncated the number of dots for readability
2...  0.717296 seconds (1.45 M allocations: 72.442 MiB, 2.20% gc time)
3...  0.187260 seconds (318.71 k allocations: 16.170 MiB, 7.07% gc time)
4...  0.189771 seconds (296.80 k allocations: 15.109 MiB)
5...  0.065658 seconds (65.23 k allocations: 3.377 MiB)
6...  0.121356 seconds (170.34 k allocations: 8.413 MiB, 33.70% gc time)
7...  0.060063 seconds (86.20 k allocations: 4.341 MiB)
8...  0.071425 seconds (97.91 k allocations: 4.866 MiB)
9...  0.076891 seconds (110.14 k allocations: 5.430 MiB, 3.53% gc time)
10...  0.083402 seconds (123.37 k allocations: 6.008 MiB)
11...  0.093608 seconds (139.10 k allocations: 6.723 MiB)
12...  0.102596 seconds (153.57 k allocations: 7.405 MiB)
13...  0.130937 seconds (175.77 k allocations: 8.430 MiB, 2.31% gc time)
14...  0.167831 seconds (219.72 k allocations: 10.430 MiB)
15...  0.261652 seconds (297.28 k allocations: 13.977 MiB, 1.04% gc time)
16...  0.414498 seconds (439.80 k allocations: 20.474 MiB, 0.74% gc time)
17...  0.729487 seconds (713.47 k allocations: 33.010 MiB, 0.32% gc time)
18...  1.480880 seconds (1.25 M allocations: 57.488 MiB, 0.50% gc time)
19...  2.784675 seconds (2.31 M allocations: 105.989 MiB, 0.36% gc time)
20...  5.612631 seconds (4.42 M allocations: 202.462 MiB, 0.21% gc time)
21... 11.262883 seconds (8.62 M allocations: 394.991 MiB, 0.21% gc time)
22... 22.504424 seconds (17.02 M allocations: 779.498 MiB, 0.18% gc time)
23... 48.030446 seconds (33.81 M allocations: 1.512 GiB, 0.16% gc time)
24... 96.648263 seconds (67.38 M allocations: 3.012 GiB, 0.15% gc time)
25...201.939618 seconds (134.50 M allocations: 6.013 GiB, 0.14% gc time)
```

Note that my result set only contains 100 rows but the execution times and especially the memory allocations skyrocket. This is very disappointing and makes `MySQL.jl` unusable for my use case.

I don't know the reason for the horrific performance. Maybe it has something to do with the way the `NamedTuples` are created [in the code](https://github.com/JuliaDatabases/MySQL.jl/blob/v0.7.0/src/types.jl#L116-L123)?

### PR DESCRIPTION
**Pull request by wookay**
I'm not sure what it for but to fix #130

### CODE REVIEW

**Comment by Sh4pe** [comment]
This does not fix #130, at least on my machine. Please run the tests of MySQL.jl in the branch [issue_130_reproduction](https://github.com/Sh4pe/MySQL.jl/tree/issue_130_reproduction). This test performs a `SELECT COUNT(*)` on an empty table. This query runs forever. Even after applying your change.

Can you confirm this?

**Comment by wookay** [comment]
in my machine, the test passed well.
```
    count_query_table = MySQL.Query(conn, "select count(*) from test_table") |> columntable
    @info :count_query_table count_query_table

    q = MySQL.Query(conn, "select * from test_table")
    _, elapsed, _, _, _ = @timed iterate(q)
    @info :elapsed elapsed

┌ Info: count_query_table
└   count_query_table = (count(*) = [0],)
┌ Info: elapsed
└   elapsed = 0.406979024
```

**Comment by wookay** [comment]
tested with this because `iterate(q)` worked well without this PR.
```
    q = MySQL.Query(conn, "select * from test_table")
    _, elapsed, _, _, _ = @timed collect(q)
    @info :elapsed elapsed
```

**Comment by Sh4pe** [comment]
Strange. My setup behaves differently. Maybe we are using different versions of MySQL.jl or Julia? What are you using?

I'm using `v0.7.0` of MySQL.jl and this Julia version:

```julia
julia> versioninfo()
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
  CPU: Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, haswell)
```

**Comment by wookay** [comment]
oh. I tested it in julia version 1.1.1. indeed, it's not worked in julia 1.2. hmm. now investigating it on julia 1.2.

**Comment by wookay** [comment]
look at this
```
const MInt = Union{Missing, Int}

names = (:f1, :f2, :f3, :f4, :f5, :f6, :f7, :f8, :f9, :f10)
types = Tuple{MInt, MInt, MInt, MInt, MInt, MInt, MInt, MInt, MInt, MInt}
nt = NamedTuple{names, types}((f1=1, f2=1, f3=1, f4=1, f5=1, f6=1, f7=1, f8=1, f9=1, f10=1))
@info :nt10 nt

names = (:f1, :f2, :f3, :f4, :f5, :f6, :f7, :f8, :f9, :f10,
         :f11, :f12, :f13, :f14, :f15, :f16, :f17, :f18, :f19, :f20)
types = Tuple{MInt, MInt, MInt, MInt, MInt, MInt, MInt, MInt, MInt, MInt,
              MInt, MInt, MInt, MInt, MInt, MInt, MInt, MInt, MInt, MInt}
nt = NamedTuple{names, types}((f1=1, f2=1, f3=1, f4=1, f5=1, f6=1, f7=1, f8=1, f9=1, f10=1,
                               f11=1, f12=1, f13=1, f14=1, f15=1, f16=1, f17=1, f18=1, f19=1, f20=1))
@info :nt20 nt
```

it takes so long by the `Union{Missing, Int}`.

**Comment by wookay** [comment]
wait for review.

**Comment by Sh4pe** [comment]
> run this in Julia 1.1, Julia 1.2.
> 
> ```
> const MInt = Union{Missing, Int}
> 
> names = (:f1, :f2, :f3, :f4, :f5, :f6, :f7, :f8, :f9, :f10)
> types = Tuple{MInt, MInt, MInt, MInt, MInt, MInt, MInt, MInt, MInt, MInt}
> nt = NamedTuple{names, types}((f1=1, f2=1, f3=1, f4=1, f5=1, f6=1, f7=1, f8=1, f9=1, f10=1))
> @info :nt10 nt
> 
> names = (:f1, :f2, :f3, :f4, :f5, :f6, :f7, :f8, :f9, :f10,
>          :f11, :f12, :f13, :f14, :f15, :f16, :f17, :f18, :f19, :f20)
> types = Tuple{MInt, MInt, MInt, MInt, MInt, MInt, MInt, MInt, MInt, MInt,
>               MInt, MInt, MInt, MInt, MInt, MInt, MInt, MInt, MInt, MInt}
> nt = NamedTuple{names, types}((f1=1, f2=1, f3=1, f4=1, f5=1, f6=1, f7=1, f8=1, f9=1, f10=1,
>                                f11=1, f12=1, f13=1, f14=1, f15=1, f16=1, f17=1, f18=1, f19=1, f20=1))
> @info :nt20 nt
> ```
> 
> it takes so long by the `Union{Missing, Int}`.
> this fixed on julia nightly that so fast.

Thanks for all the effort you put into this, @wookay! Do you know if this is a known Julia 1.2 problem?

**Comment by wookay** [comment]
shorter version to test.
```
Tuple{Vararg{Union{Missing,Int},20}}((1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1))
```

in this regard, there was an issue in Julia about 3 weeks ago.
Inference performance regression vs 1.2 (NeuralNetDiffEq)
https://github.com/JuliaLang/julia/issues/33337

**Comment by Sh4pe** [comment]
I've just checked: the patches in this pull request indeed fix #130. Maybe a quick test for this should be included?

**Comment by quinnj** [comment]
Thanks for digging around and testing htis @wookay and @Sh4pe, and sorry for the slow responses from me; I've been a bit tied up in other things lately. I think this solution is fine for now. If I can find time, I'd like to overhaul the package a bit and I'll probably change the "row" type from NamedTuple to something like `MySQL.Row` that would avoid the over-typing of NamedTuple.

**Pull request merged**
